module.exports = {
  Container: { conversionFunction: require('./Container') },
  TextBlock: { conversionFunction: require('./TextBlock') },
  Image: { conversionFunction: require('./Image') },
  Media: { conversionFunction: require('./Media') },
  MediaSource: { conversionFunction: require('./MediaSource') },
  ColumnSet: { conversionFunction: require('./ColumnSet') },
  Column: { conversionFunction: require('./Column') },
  FactSet: { conversionFunction: require('./FactSet') },
  ImageSet: { conversionFunction: require('./ImageSet') },
  'Action.OpenUrl': { conversionFunction: require('./Action.OpenUrl') },
  'Action.Submit': { conversionFunction: require('./Action.Submit') },
  'Action.ShowCard': { conversionFunction: require('./Action.ShowCard') },
  'Input.Text': { conversionFunction: require('./Input.Text') },
  'Input.Number': { conversionFunction: require('./Input.Number') },
  'Input.Date': { conversionFunction: require('./Input.Date') },
  'Input.Time': { conversionFunction: require('./Input.Time') },
  'Input.Toggle': { conversionFunction: require('./Input.Toggle') },
  'Input.ChoiceSet': { conversionFunction: require('./Input.ChoiceSet') },
  'Input.Choice': { conversionFunction: require('./Input.Choice') }
}
