module.exports = {
  apiLookup: require('./api-lookup'),
  checkboxList: require('./checkbox-list'),
  address: require('./address'),
  date: require('./date'),
  currency: require('./currency'),
  dateTime: require('./date-time'),
  fileUpload: require('./file-upload'),
  header: require('./header'),
  image: require('./image'),
  map: require('./map'),
  questionnaire: require('./questionnaire'),
  number: require('./number'),
  radio: require('./radio'),
  richtext: require('./richtext'),
  select: require('./select'),
  signature: require('./signature'),
  slider: require('./slider'),
  stickyNote: require('./sticky-note'),
  switch: require('./switch'),
  text: require('./text'),
  textarea: require('./textarea'),
  time: require('./time')
}
